#! /bin/bash
# bish & bash mix compiler

if [ ! -d "$1.mbish" ]
then
	echo "Cannot find the mbish directory" 1>&2
	exit 1
fi

echo "#! /bin/bash" > $1

if [[ "$1" != *.sh ]]
then
	chmod 755 "$1"
else
	chmod 644 "$1"
fi

for bishsrc in $1.mbish/*
do
	case "$bishsrc" in
		(*.bish)	bish "$bishsrc" >> $1;;
		(*.bil)	bish -l "$bishsrc" >> $1;;
		(*)	cat "$bishsrc" >> $1
	esac
done
