#! /bin/bash
# bish & bash mix compiler

if [ ! -d $1.mbish ]
then
	echo "Cannot find the mbish directory" 1>&2
	exit 1
fi

echo "#! /bin/bash" > $1
chmod 755 $1

for i in $1.mbish/*
do
	if [ "`basename $i | cut -d . -f 2-`" = "bish" ]
	then
		bish $i >> $1
	else
		cat $i >> $1
	fi
done

